// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeqtc-YtQCrUphb-ldbVf3coUoIYS8t3U',
    appId: '1:424917772550:android:237f2a77027f9bf1061687',
    messagingSenderId: '424917772550',
    projectId: 'todo1-c60d9',
    storageBucket: 'todo1-c60d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXE6mKj3ue44dxigZscdiUEcgd4Zoskhw',
    appId: '1:424917772550:ios:3c9f3ad3f0cfbd81061687',
    messagingSenderId: '424917772550',
    projectId: 'todo1-c60d9',
    storageBucket: 'todo1-c60d9.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1UmVvzQWD4Q_SYvO-3jKb-gafTvsa5p0',
    appId: '1:424917772550:web:300148792984ff7b061687',
    messagingSenderId: '424917772550',
    projectId: 'todo1-c60d9',
    authDomain: 'todo1-c60d9.firebaseapp.com',
    storageBucket: 'todo1-c60d9.appspot.com',
  );
}
